# Generated by Django 4.2.6 on 2023-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name_of_company', models.CharField(max_length=255)),
                ('type_of_procurement', models.CharField(choices=[('Goods', 'товары'), ('work', 'работы'), ('services', 'услуги')], max_length=255)),
                ('purchase_name', models.CharField(max_length=255)),
                ('planned_amount', models.FloatField()),
                ('procurement_method', models.CharField(choices=[('One stage', 'неограниченный'), ('Simplified', 'простой')], max_length=255)),
                ('date_published', models.DateTimeField()),
                ('bids_submission_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'активный'), ('canceled', 'отмененный'), ('completed', 'завершенный')], max_length=15)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
