# Generated by Django 4.2.6 on 2023-11-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
